version: "3.9"

services:
  db:
    image: postgres:9.6.23-alpine3.14
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:6.2.6-bullseye
    container_name: redis
    ports:
      - '6379:6379'
  web:
    build: ./web
    command: bash -c "
              python manage.py migrate
              && python manage.py runserver 0.0.0.0:8080
              & celery -A web beat -l INFO
              & celery -A web worker -l INFO
            "
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis